### ISSUE TITLE
After build uglify plugin fires exception in every file

### ISSUE THREAD

**Issue by DrBoria** [iamolegga/prettier-loader#10]
Every time I tried to build after adding your loader I got problem like this:

ERROR in app/ad64cd4cb288185aae11.js from UglifyJs
Unexpected token: punc ()) [app/ad64cd4cb288185aae11.js:486,0]

With every file in build.

**Comment by iamolegga** [comment]
I think this is the case of bad sequence of loaders, i need to see your webpack config

**Comment by DrBoria** [comment]
Probably.
For now list of loaders looks like this:
http://take.ms/eH0b4

**Comment by iamolegga** [comment]
Sure, you could add property `enforce: pre` to the rule object, or move it to be first in array of rules

**Comment by DrBoria** [comment]
I'v add `enforce: 'pre'` and replace to the first position, but still same error:
`    ERROR in sw.js from UglifyJs
    Unexpected token: punc ()) [sw.js:619,0]
`
Even after reinstalling all node_modules and deleting package-lock.json

**Comment by iamolegga** [comment]
need to see config again

**Comment by DrBoria** [comment]
Here it is
http://take.ms/Z71Sb

**Comment by iamolegga** [comment]
Ok, try to add `exclude: /node_modules/`

**Comment by DrBoria** [comment]
Yepp, thanks)
It works.
Probably better if you will add comment in install instructions. Because prettier by default exclude node_modules
