### ISSUE TITLE
Please give me the npm package name 'prettier-loader'

### ISSUE THREAD

**Issue by rchaser53** [iamolegga/prettier-loader#11]
I'm sorry to say that i think this package is not maintain now.
If you don't want to maintain 'prettier-loader', please give me the name 'prettier-loader' for npm.
Now I create the package [prettier-loader](https://github.com/rchaser53/prettier-loader).
thank you.

**Comment by rchaser53** [comment]
my prettier-loader supports `.prettierignore` and `webpack-dev-server`(live reloading).

**Comment by iamolegga** [comment]
This package is still maintaining, you can publish your own package under any other name, so I’m closing this issue
