### ISSUE TITLE
How to use with the .prettierrc file

### ISSUE THREAD

**Issue by c0d3x** [iamolegga/prettier-loader#16]
- [ ] Question: How do I use the .prettierrc file inside the webpack.config.js and inside the prettier-loader options?

Do I need to make additional package.json file changes?
Do I need to reference the .prettierrc inside the options: {} ?

```js
This works, but I want it to read from .prettierrc file that is supposedly supported.
config.module.rules.push({
    test: /\.(js|jsx)?$/,
    use: {
        loader: 'prettier-loader',
        options: {
            parser: "babylon",
            printWidth: 100,
            singleQuote: true,
            tabWidth: 4
        }
    }
});
```

Now I get this when I run npm start:
**"No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred."**

Even though I have my .prettierrc file with this setup:
```json
{
    "parser": "babylon",
    "printWidth": 100,
    "singleQuote": true,
    "tabWidth": 4
}
```

**Comment by iamolegga** [comment]
You can remove the `options` property in webpack rule, and leave it in `.prettierrc` inside root directory of your project. It should just work. And what about warning, I guess this is something with prettier itself, I'll check it out. Have you tried the latest versions of both prettier and prettier-loader?
