### ISSUE TITLE
error with babel

### ISSUE THREAD

**Issue by AminAhmadyDeveloper** [iamolegga/prettier-loader#164]
_If you know how to fix the issue, make a pull request instead._

- hi ,  I tried using 3.3.0 with my webpack using babel loader and when i add prettier loader to my webpack config file error happens

works fine without prettier loader

here my webpack config:

`const ESLintPlugin = require('eslint-webpack-plugin')

module.exports = {
    mode: 'development',
    context: __dirname + "/src/js",
    entry: "./script.js",
    output: {
        path: __dirname + "/build",
        filename: "bundle.js"
    },
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            },
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'prettier-loader',
                }
            }
        ]
    },
    plugins: [new ESLintPlugin({})]
}`

and this is my test js file to be compiled:

`async function download(url, ok) {
    if (ok) {
        return { name: 'Amin', family: 'Ahmady', website: `http://${url}` }
    } else {
        throw new Error('Downloading Failed!')
    }
}

async function save(data, ok) {
    if (ok) {
        return {
            user: data,
            ok: !ok,
        }
    } else {
        throw new Error('Save Failed!')
    }
}

download('github.com', true)
    .then((data) => save(data, true))
    .then((data) => console.log(data))
    .catch((err) => console.log(err.message))
`

where is the isseu?

my prettier config if needed:
`# Ignore artifacts:
build
node_modules`

**Comment by AminAhmadyDeveloper** [comment]
update: changing async funs to promise solved the problem but async also works without prettier loader

**Comment by iamolegga** [comment]
could you please format your code, because it's unreadable now

**Comment by AminAhmadyDeveloper** [comment]
thanks for quick response sir, after  I double checked my webpack config file I find out it was my configuration mistake somewhere
 LOVES <3
