### ISSUE TITLE
prettier.config.js file spesify path webpack 

### ISSUE THREAD

**Issue by muradsofiyev** [iamolegga/prettier-loader#18]
- [x] Question:  My prettier.config.js not root folder instead of other config folder. And I want change prettier config file path 
In prettier documentation --config ".env/prettier.config.js"  work 
But when I use prettier-loader options config webpack return error 

> Ignored unknown option `{ "configFile": ".env/prettier.config.js"}

**Comment by iamolegga** [comment]
Yes, if it's not in one of file's parent folder, it will not be resolved now.
As quick decision you can move your prettier options to loader options, or wait when I'll add this option to loader, I think It will take a few days.

**Comment by iamolegga** [comment]
Hi, just checked again, and find out, that you can do now:

```
// webpack.config.js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: {
          loader: 'prettier-loader',
          exclude: /node_modules/,
          options: {
            // options according to https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options
            resolveConfigOptions: {
              config: 'path/to/prettier.config.file'
            }
          },
        }
      }
    ]
  }
};
```

So, just check, that you use the last version.

Closing.

**Comment by iamolegga** [comment]
I'll add this to documentation, thanks for your issue 👍
