### ISSUE TITLE
Wrong engine version

### ISSUE THREAD

**Issue by tarwich** [iamolegga/prettier-loader#2]
Currently the `engine` is set to `8.4.0`, which prevents installation on anything else. For example, we're unable to install on `8.4.1`

**Comment by iamolegga** [comment]
Hi, @tarwich, thanks for your issue, but here I use `eslint-plugin-node`, and it need to set up `engines` in `package.json` to understand what's node version.

Anyway, I think we can change it to LTS version and upper, what do you think about that?

**Comment by iamolegga** [comment]
Thanks a lot, tomorrow I'll test it with different node's major version, and merge it. 👍

**Comment by tarwich** [comment]
Awesome, man!

**Comment by iamolegga** [comment]
Hi! I just merged your PR, now I'm gonna solve some eslint errors and soon will make new version

**Comment by iamolegga** [comment]
Just published 1.2.0
