### ISSUE TITLE
Disabling prettier-loader when webpack starts

### ISSUE THREAD

**Issue by astik** [iamolegga/prettier-loader#29]
- [x] I tried using [the latest stable version of prettier-loader](https://www.npmjs.com/package/prettier-loader)
- [x] I've read [readme](https://github.com/iamolegga/prettier-loader/blob/master/README.md)

- [x] Enhancement: speedup webpack start up by disabling prettier-loader (just for bootstraping)

---

In a project, i have a lot of HTML files defined as entry files thanks to *html-webpack-plugin*.
Loaders for HTML files are *prettier-loader* and *html-loader*.
Each HTML file needs 2 sec of processing by prettier (triggered by prettier-loader.

Cold start will go higher and higher everytime we add new entry HTML files.
As HTML are supposed to be prettified each time we save a file, the processing at startup is unneeded.
Disabling / skipping prettifying at startup would make the startup process way faster.

---

Naive (still working) approach: we could wait x milliseconds before enabling prettier.

```js
let skip = true;
setTimeout(() => {
  console.log("prettier is now enabled")
  skip = false
}, 5000)

module.exports = async function(source, map) {
  this.cacheable();
  const callback = this.async();

  if (skip) {
    return callback(null, source, map);
  }
```

**Comment by astik** [comment]
A demo project has been created : https://github.com/astik/prettier-loader-demo-issue-29

**Comment by iamolegga** [comment]
I think timeout with hardcoded value is not so good.
But we can create `Set` of files paths that should be processed.
On start `Set` will be empty.

After that we can check, if filepath is not in set, skip check, and add it to set.
On next handling this `Set` will containt this file path, and all prettier processing will work.

And of course we should hide this feature by new flag in loader options.

Ok?
