### ISSUE TITLE
Ignore/disable prettier didn't works

### ISSUE THREAD

**Issue by DrBoria** [iamolegga/prettier-loader#9]
I tried to add comments like:
// prettier-ignore
// prettier-disable
/* eslint-disable prettier/prettier */
Or add external file '.prettierignore'

But your loder still modify file I'd like to ignore. Is there any way to ignore files when modifying?

**Comment by iamolegga** [comment]
strange, what versions of prettier and prettier-loader do you use?

**Comment by iamolegga** [comment]
and could you provide examples of code with comments?

**Comment by DrBoria** [comment]
"prettier": "^1.10.2",
    "prettier-loader": "^2.0.1",

Well. I user prettier loader with webpack-dev-server. And I'v got file with react routes. Each route is longer, than 120 symbols (that I set in prettier-loader config), but event after adding 'ignore', 'disable' etc. comments it changes file with routes.

Config for prettier loader in webpack
 `
{
      test: /\.jsx?$/,
      use: {
        loader: 'prettier-loader',
        options: {
          useTabs: false,
          tabWidth: 2,
          singleQuote: true,
          printWidth: 120,
          trailingComma: 'all',
          bracketSpacing: true,
          arrowParens: 'always'
         },
      }
    }
`

**Comment by iamolegga** [comment]
Could you please provide example of jsx code where you write comments

**Comment by iamolegga** [comment]
I mean *how* you write comments inside jsx?

**Comment by DrBoria** [comment]
Like this
http://take.ms/JbJ8w
Just at the top of the file.

**Comment by iamolegga** [comment]
Thanks, I think I'll add test for this case today, and take a look what's going on

**Comment by iamolegga** [comment]
Sorry for so long waiting, as @rchaser53 just wrote in another issue, his own version of prettier-loader does support of .prettierignore files, so you can try it:
https://github.com/rchaser53/prettier-loader, or wait for a week (I hope so) until I’ll fix it in this package

**Comment by iamolegga** [comment]
So, I just added test for ignoring prettier using comments, and it works, see [this commit](https://github.com/iamolegga/prettier-loader/commit/556666b8f0e252d2e3aace1201c1b532bea06600), because it's the same as if you just tried to run prettier-cli on your code.
The next thing is to check/fix work with `.prettierignore` file, working on it

**Comment by iamolegga** [comment]
What about trying to prevent formatting with comment, I think the problem that

> A JavaScript comment of // prettier-ignore will exclude the next node in the abstract syntax tree from formatting.

And _the next node in the abstract syntax tree_ in [your example](http://take.ms/JbJ8w) is `// prettier-disable` and all next code will be formatted.

So yes, if you want to ignore the whole file it's better to keep it in `.prettierignore`

**Comment by iamolegga** [comment]
fixed in #12 

npm version `2.1.0`
